// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Schedule.Migrations.Migrations
{
    [DbContext(typeof(ScheduleContext.ScheduleContext))]
    partial class ScheduleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models+Auditory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Floor");

                    b.Property<bool>("HasPower");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Auditories");
                });

            modelBuilder.Entity("Domain.Models+Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AuditoryId");

                    b.Property<DateTime>("Date");

                    b.Property<long?>("SubjectId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("AuditoryId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Domain.Models+Identity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("EventId");

                    b.Property<long?>("EventId1");

                    b.Property<string>("FullName");

                    b.Property<bool>("IsAlternative");

                    b.Property<string>("ShortName");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("EventId1");

                    b.ToTable("Identites");
                });

            modelBuilder.Entity("Domain.Models+Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brief");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.Models+Teacher", b =>
                {
                    b.Property<long>("TeacherId");

                    b.Property<long>("SubjectId");

                    b.Property<long>("GroupId");

                    b.Property<int>("EventType");

                    b.HasKey("TeacherId", "SubjectId", "GroupId", "EventType");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Domain.Models+Event", b =>
                {
                    b.HasOne("Domain.Models+Auditory", "Auditory")
                        .WithMany()
                        .HasForeignKey("AuditoryId");

                    b.HasOne("Domain.Models+Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("Domain.Models+Identity", b =>
                {
                    b.HasOne("Domain.Models+Event")
                        .WithMany("Groups")
                        .HasForeignKey("EventId");

                    b.HasOne("Domain.Models+Event")
                        .WithMany("Teachers")
                        .HasForeignKey("EventId1");
                });
#pragma warning restore 612, 618
        }
    }
}
