// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Schedule.Migrations.Migrations
{
    [DbContext(typeof(ScheduleContext.ScheduleContext))]
    partial class ScheduleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Domain.Models+Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Auditory");

                    b.Property<DateTime>("EndTime");

                    b.Property<long>("GroupId");

                    b.Property<DateTime>("StartTime");

                    b.Property<long>("SubjectId");

                    b.Property<string>("Teachers");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Domain.Models+Identity", b =>
                {
                    b.Property<long>("Id");

                    b.Property<int>("Type");

                    b.Property<string>("Name");

                    b.HasKey("Id", "Type");

                    b.ToTable("Identites");
                });

            modelBuilder.Entity("Domain.Models+Subject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Brief");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Domain.Models+Teacher", b =>
                {
                    b.Property<long>("TeacherId");

                    b.Property<long>("SubjectId");

                    b.Property<long>("GroupId");

                    b.Property<int>("EventType");

                    b.HasKey("TeacherId", "SubjectId", "GroupId", "EventType");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
